# NEED TO TEST

version: '3.8'
services:
  ULBDiscordBot:
    image: bepolytech/ulbdiscordbot
    container_name: ULBDiscordBot
    #build:
    #  context: .
    #  image: ulbdiscordbot
    #  dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./ # needs verifying
    restart: always
    #command: python main.py
