# TODO, AND NEED TO TEST

version: '3.8' 
services:
  ULBDiscordBot:
    name: ULBDiscordBot
    #image: bepolytech/ulbdiscordbot
    build:
      context: .
      #image: ulbdiscordbot
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/ulbdiscordbot:rw
    #command: python main.py
